问题排查
Exception in connection from optimus86axx/10.240.86.xx:7337
java.io.IOException: Connection reset by peer
Still have xx requests outstanding when connection from optimus86axx/10.240.86.xx:7337 is closed
Resubmitting ShffleMapStage 2 due to fetch failure

Lost executor xxx on optimus86axx: Unable to create executor due to Unable to register with external shuffle server due to : java.util.concurrent.TimeoutException: Timeout waiting for task
Executor lost: xxx (epoch 1)